# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  testing: circleci/welcome-orb@0.4.1
  aws-s3: circleci/aws-s3@x.y
# Orchestrate or schedule a set of jobs
jobs:
  build: #This isnt really needed since this project is just a static html site, but I'll leave it as a placeholder
    docker:
      - image: cimg/node:14.10.1 
        auth:
          username: $DockerUsername
          password: $DockerPassword
    steps:
      - checkout
      - run: yarn install
  test:
    docker:
      - image: cimg/node:14.10.1 
        auth:
          username: $DockerUsername
          password: $DockerPassword
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
  deploy:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          to: 's3://amazingwebsite'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: bucket/build_asset.txt
          to: 's3://amazingwebsite'
workflows:
  testing:
    jobs:
      - build
      - test
      - deploy
